# Edits to use `global.toml` on a Windows system (mostly path changes)

[alacritty.files]
"config/alacritty/config.toml" = "~/AppData/Roaming/alacritty/alacritty.toml"

[bash.files]
"config/bash/config.sh" = "~/scoop/apps/git/current/etc/bash.bashrc"

[btop.files]
"config/btop/config.conf" = ""
"config/btop/windows.conf" = "~/scoop/persist/btop-lhm/btop.conf"

[git.variables]
autocrlf = "true"
gh_path = "'C:\\\\Users\\\\max\\\\scoop\\\\apps\\\\gh\\\\current\\\\bin\\\\gh.exe'"

[helix.files]
"config/helix/config.toml" = "~/appdata/roaming/helix/config.toml"
"config/helix/themes" = {target="~/appdata/roaming/helix/themes", type="symbolic", recurse=false}

[ncmpcpp.files]
"config/ncmpcpp/config.conf" = ""  # replace ncmpcpp with ncmpc on Windows
"config/ncmpcpp/ncmpc.conf" = "~/.ncmpc/config"

[pypoetry.files]
"config/pypoetry/config.toml" = "~/AppData/Roaming/pypoetry/config.toml"
