includes = []
packages = [
  "river", "waybar", "dunst", "swaylock", "kanshi", "tofi", "wezterm",
  "bash", "tmux", "fastfetch", "gtk", "grub", "swappy",
  "helix", "pypoetry", "git", "cava", "btop", "mpd", "ncmpcpp"
]

[files]

[variables]
mpd_host = "192.168.0.8"
music_path = "/mnt/smb/athena/music"


